import streamlit as st
import requests 
import datetime

import sys

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title = "Travel Planner Agentic app",
    page_icon = "✈️",
    layout = "centered",
    initial_sidebar_state = "expanded"
)

st.title("✈️ AI Trip Planner and Expense Estimator")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I help you in planning your trip today? Let me know where do you want to go!🌍")

with st.form(key="query_form",clear_on_submit=True):
    user_input = st.text_area("Enter your travel plan request here:",placeholder="E.g., Plan a 5-day trip to Paris including sightseeing, accommodation, food, and transportation with an estimated budget.")
    submit_button = st.form_submit_button(label="Send")

if submit_button and user_input.strip() != "":
    try:
        with st.spinner("Planning your trip...✈️🌍"):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "Sorry, I couldn't get a response.")
            markdown_content = f"""# Trip Plan and Expense Estimate
            #**Generated:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            #**Created by:** AI Trip Planner Agentic App
            -----

            {answer}

            -----
            *This document was generated by an AI-powered Trip Planner and Expense Estimator.*"""
            st.markdown(markdown_content)
        else:
            st.error("Bot failed to respond: "+ response.text)
    except Exception as e:
        raise f"The response failed due to error: {str(e)}"